### ISSUE TITLE
Inference using pretrained models

### ISSUE THREAD

**Issue by FraPochetti** [Charleshhy/One-shot-Human-Parsing#4]
Hi, 
first of all, thanks a lot for sharing your work. Really impressive!
I have 2 questions please:

1. I am not sure if I get the purpose/capabilities of this approach correctly but, is the model able to handle one single input image at inference time? e.g. during [training](https://github.com/Charleshhy/One-shot-Human-Parsing/blob/04cd3c14859ea45722377fce5403b686f82269c9/exp/train.py#L286) it seems that both `query` and `support` images/masks are needed. For inference, what we want though, is to be able to submit a _single_ (or batch) picture of a person and have the mask as output (image IN -> mask OUT). Is this supported?
2. If yes, do you have a code snippet providing preprocessing+inference+postprocessing?

Thanks and have a great day

**Comment by Charleshhy** [comment]
Hi,

Thanks for your attention for our project :D

Our project is on one-shot human parsing, the aim is to parse human as indicated by the `support` and `support mask`. Since the fine-grained classes might be different between training and inference, both `query`, `support` and `support mask` are required in both training and inference.

Kind regards,
Haoyu

**Comment by FraPochetti** [comment]
Got it thanks!
