### ISSUE TITLE
some questions about metrics

### ISSUE THREAD

**Issue by dandanAD** [Charleshhy/One-shot-Human-Parsing#8]
I successfully reproduced your code on the atr dataset, but the effect did not reach the effect mentioned in your article, as shown in the figure below, epoch=50, batch=2, gpus=2, because batch=2 will report an error, I made a simple modification to the code, what else can I do to achieve the effect of your article. Also, which part of the code output should I look at, agm or npm, where mean miou is the human miou in the paper?
Looking forward to your reply！

**Comment by dandanAD** [comment]
![image](https://user-images.githubusercontent.com/85143391/162116802-7ee9b6b6-92b4-45c7-9be7-445ee73242ec.png)

**Comment by Charleshhy** [comment]
Hi dandanAD,

1. The batch size is a must. The reason is that we are using [Sync BN](https://pytorch.org/docs/stable/generated/torch.nn.SyncBatchNorm.html), and the higher the batch size is, the more stable BN parameters are learned. If your GPU memory is large enough, I would recommend you to keep the batch size as 2 and use a single GPU instead.

2. We should use NPM as the final prediction and yes, mean mIoU is the human mIoU. 

3. The one-shot datasets are not large enough thus the performance variance might be large. You can try different seeds to seek for better performance :) 

Kind regards,
Haoyu

**Comment by dandanAD** [comment]
> Hi dandanAD,
> 
> 1. The batch size is a must. The reason is that we are using [Sync BN](https://pytorch.org/docs/stable/generated/torch.nn.SyncBatchNorm.html), and the higher the batch size is, the more stable BN parameters are learned. If your GPU memory is large enough, I would recommend you to keep the batch size as 2 and use a single GPU instead.
> 2. We should use NPM as the final prediction and yes, mean mIoU is the human mIoU.
> 3. The one-shot datasets are not large enough thus the performance variance might be large. You can try different seeds to seek for better performance :)
> 
> Kind regards, Haoyu

thank you for your reply
